### PR TITLE
fix for txt output length of plain PQ key material

### LINKED ISSUE #267: Printing a Dilithium3 key file results in an incomplete output, omitting the last 4 bytes of the keys.
When printing out the `Dilithium3` key file using the `openssl pkey -text -in sample.key` command, the output text omits the last 4 bytes from both **private** and **public** keys. These bytes are valid and should be printed. The following reproduction steps will show the presence of the missing bytes in the DER key file.

Note that a Dilithium3 key file contains both public and private keys, and so the `pkey -text` command fails to print the last 4 bytes for ***both***.

**To Reproduce**
```shell
# Generate cert and key.
openssl req -x509 -new -newkey dilithium3 -keyout sample.key -out sample.crt -nodes -subj "/CN=sample"
# The output from this command is missing the last 4 bytes from both the public key and secret key, totaling 8 bytes.
openssl pkey -text -in sample.key
# Convert the key file to DER.
openssl pkey -in sample.key -outform DER -out sample.key.der
# Print the DER file.
xxd -i sample.key.der
```   
 

**Expected behavior**  

Below is the end of the sample output from the `openssl pkey -text -in sample.key` command:

```text
...
    53:a3:bf:dd:bd:4a:4d:ad:8b:43:7c:a2:1b:7f:51:
    db:19:69:45:2c:5d:cd:12:d9:a8:a4:3c:61:42:c7:
    84:6c:b1:fa:5f:0a:7c:34:f1:45:84:81:d2
```

Compare it to the `sample.key.der`:

```text
...                                         0x53, 0xa3, 0xbf, 0xdd, 0xbd,
  0x4a, 0x4d, 0xad, 0x8b, 0x43, 0x7c, 0xa2, 0x1b, 0x7f, 0x51, 0xdb, 0x19,
  0x69, 0x45, 0x2c, 0x5d, 0xcd, 0x12, 0xd9, 0xa8, 0xa4, 0x3c, 0x61, 0x42,
  0xc7, 0x84, 0x6c, 0xb1, 0xfa, 0x5f, 0x0a, 0x7c, 0x34, 0xf1, 0x45, 0x84,
  0x81, 0xd2, 0xd5, 0x36, 0x09, 0xf8
...
```

Note the last missing bytes: `0xd5, 0x36, 0x09, 0xf8`. So expecting the following output:
```text
...
    53:a3:bf:dd:bd:4a:4d:ad:8b:43:7c:a2:1b:7f:51:
    db:19:69:45:2c:5d:cd:12:d9:a8:a4:3c:61:42:c7:
    84:6c:b1:fa:5f:0a:7c:34:f1:45:84:81:d2:d5:36:09:f8
```

`The same issue occurs for the other key in this file.`

**Environment:**
 - OS: MacOS 10.15.7
```shell
➜ openssl version
OpenSSL 3.1.2 1 Aug 2023 (Library: OpenSSL 3.1.2 1 Aug 2023)
➜ openssl list -providers
Providers:
  default
    name: OpenSSL Default Provider
    version: 3.1.2
    status: active
  oqsprovider
    name: OpenSSL OQS Provider
    version: 0.5.2-dev
    status: active

```

### PR DESCRIPTION
**Pull request by baentsch**
Fixes #267.

### CODE REVIEW

File: oqsprov/oqs_encode_key2any.c [hunk 1]
```diff
@@ -1160,7 +1160,7 @@ static int oqsx_to_text(BIO *out, const void *key, int selection)
     }
 
     if ((selection & OSSL_KEYMGMT_SELECT_PRIVATE_KEY) != 0) {
-        int classic_key_len = 0;
+        int classic_key_len = 0 - SIZE_OF_UINT32;
```
Comment (dstebila) [inline oqsprov/oqs_encode_key2any.c:1163]: Initializing a length variable to a negative number, seems counterintuitive.  I'll assume what you've done indeed fixes the bug, but I wonder if there's a more natural way, or at least if there should be a comment explaining this counterintuitive step.

Comment (dstebila) [reply oqsprov/oqs_encode_key2any.c:1163]: Perhaps you can walk me through the logic in the subsequent: does line 1169 add to classic_key_len, so that on 1171 it is now non-negative?

Comment (baentsch) [reply oqsprov/oqs_encode_key2any.c:1163]: Yes. The code is shared between hybrid (numkeys>1) and plain PQ keys. The classic_key_len element is (obviously) only relevant for hybrid keys (as is, err, should be, the 4 bytes storing it). This pattern is not unusual throughout provider -- but I agree that initializing a length to a negative value (to get it added back in the subsequent keytype independent subtraction for plain PQ keys) may be "surprising". Will revise the code for easier understanding -- but doing this "for real", i.e., in the complete code base, will probably require many more changes...

**Review by dstebila — APPROVED** [review]
